export enum AuditAction {
  // Authentication
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGIN_FAILED = 'LOGIN_FAILED',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
  
  // Dashboard
  DASHBOARD_VIEW = 'DASHBOARD_VIEW',
  DASHBOARD_REFRESH = 'DASHBOARD_REFRESH',
  
  // CRUD Operations
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  READ = 'READ',
  
  // User Management
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_ROLE_CHANGE = 'USER_ROLE_CHANGE',
  USER_LIST = 'USER_LIST',
  
  // Settings
  SETTINGS_UPDATE = 'SETTINGS_UPDATE',
  
  // Export/Download
  DATA_EXPORT = 'DATA_EXPORT',
  DATA_DOWNLOAD = 'DATA_DOWNLOAD',
  
  // Other
  BULK_ACTION = 'BULK_ACTION',
  API_CALL = 'API_CALL',
}
